### ISSUE TITLE
Setup Problem

### ISSUE THREAD

**Issue by JackTerok** [MikeBishop/MMM-Powerwall#8] opened 2020-07-19 12:01 UTC
I've tried to set up MMM-Powerwall and it shows the modules on screen. But there is no data displayed. Just 0 and NaN. 

![conf](https://user-images.githubusercontent.com/10469129/87874183-1ae3cb80-c9c8-11ea-81ae-1d01788fde24.png)

This is my config. Username and password are deleted here but were present during setup. 
Also the token file in the folder got not created. Username, password and IP are definitively correct.

**Comment by MikeBishop** [comment] 2020-07-19 13:31
First things first, did you restart MM on the server so the node_helper is running? If so, I'd try adding `debug: true` to your config to get a LOT more output in the debug console and at the MM command line to see if it says what's wrong.

**Comment by JackTerok** [comment] 2020-07-19 15:04
So i did a complete restart of the pi and now it shows at least some information. Battery state and some of the circles are filled. Solar Production and House consumption is still at NaN W. Also the token file still got not created.

I also tried manually creating the token file and adding the token key but that also didnt work.

**Comment by MikeBishop** [comment] 2020-07-19 15:49
I think I found at least part of the issue -- without the home location set, it was hitting an exception.  I wasn't able to repro the auth issue, but let's start with the fix at 68106ea.

**Comment by JackTerok** [comment] 2020-07-19 16:21
Nice. That solved the problem. Just out of curiosity. If I only want to get powerwall data access to the account should not be necessary. Or are there datapoints you can only get from the server and not the local network?

**Comment by JackTerok** [comment] 2020-07-19 16:29
Nevermind. It's not completely fixed. The values show up but don't update no matter the update interval in the config.

**Comment by MikeBishop** [comment] 2020-07-19 16:43
The Powerwall locally doesn't keep any history except a set of counters. If the mirror is online at midnight, it snaps those counters and uses them to show the usage so far; otherwise (like at startup) it fetches the current day's data to calculate those base values. The self-powered number is purely cloud-based; that won't show up without the Tesla account. Lastly, the current charge is calculated a little differently between cloud and local; if cloud access is available, it uses that so it matches the app. (This also is why the battery level will change a few percent a few seconds after startup.

**Comment by JackTerok** [comment] 2020-07-19 16:47
Ok, that makes sense. But since the current values come from the local IP, those values not moving is a bug and not an error on my part. Atleast I would assume so.

**Comment by MikeBishop** [comment] 2020-07-19 17:37
Did you see anything in the console after adding debug to the config?

**Comment by JackTerok** [comment] 2020-07-19 17:48
Output:
![out](https://user-images.githubusercontent.com/10469129/87881318-be4cd480-c9f8-11ea-9a64-ee1fb7d16d59.png)

Config: 
![conf](https://user-images.githubusercontent.com/10469129/87881320-c3118880-c9f8-11ea-8897-6d9d0789a397.png)


There seems to be a few discrepancies between log and config.

**Comment by MikeBishop** [comment] 2020-07-19 18:16
I think I found it.  The docs say `teslaApiUsername` and `teslaApiPassword`; the code says `teslaAPIUsername` and `teslaAPIPassword`; note the capitalization difference.  I've updated the docs to match the code, since it's used in more places.  Change your "pi"s to "PI"s and hopefully you'll be in business.

**Comment by MikeBishop** [comment] 2020-07-19 18:19
Also, you might find those refresh intervals to be a bit too fast for the animations to keep up.  I wouldn't go much below three seconds at the lowest.

**Comment by JackTerok** [comment] 2020-07-19 18:35
Token creation is now working. Also, the log now shows more info. Found an error on my part. While we only have 1 powerwall we did switch out a broken Gateway so there are 2 sideIds registered to our account. Needed to specify the correct one. I also get valid api responses. In the UI the SelfPowered Circle is now correctly displayed. But all other Values aren't displayed anymore. Back to NaN.

**Comment by MikeBishop** [comment] 2020-07-19 18:37
Makes me think you're getting data back and something's breaking client-side then.  Try connecting from a browser and opening the console?  (F12 in Chromium-based browsers)

**Comment by JackTerok** [comment] 2020-07-19 18:45
![exept](https://user-images.githubusercontent.com/10469129/87882545-d7f21a00-ca00-11ea-8946-9eedb2b61171.png)

**Comment by JackTerok** [comment] 2020-07-19 18:55
Hmm. I reloaded the page and now it connected. Now all values are getting shown. But they still don't update.
And i got this:
![err2](https://user-images.githubusercontent.com/10469129/87882687-2653e880-ca02-11ea-93f4-5d2ebca66e5a.png)

**Comment by JackTerok** [comment] 2020-07-19 19:01
I tested a bit. on some reloads it can't get the local powerwall data. And I get back empty responses. Maybe check if the response is empty and if so try to get the data again instead of trying to process the empty array.

**Comment by MikeBishop** [comment] 2020-07-19 20:01
ead067a makes the local code more resilient to not having data; the socket.io code usually just indicates transient connectivity between client and server.  That probably just squelches the error instead of actually fixing why you're not getting data, though.  Are you seeing any events in the Console that start with "Received Aggregates"?  Are you getting errors on the server side (try `pm2 logs MagicMirror` if you're using pm2.

**Comment by JackTerok** [comment] 2020-07-19 20:12
I'm not getting any errors serverside. But sometimes I get an empty Array as the response for the aggregates data. On reload, it gets the proper aggregates data. The problem here is it gets the data only once then waits indefinetly.

**Comment by MikeBishop** [comment] 2020-07-19 20:32
Hm.  I don't think it's that simple.  There are at least two paths that should ensure the client continues requesting data.  First, the notification handler schedules the next request every time it receives the notification (line 301 in this case).  Second, every time updateData() runs, it checks whether any requested data is overdue by more than five seconds and re-requests it.  I tried turning mine to the shorter update intervals you're using to see if there's a race condition there, but I haven't yet encountered it.

Are you seeing the empty response in the "Received Aggregates" line in the console, or on the output server-side?  Can you paste in what you're seeing?

**Comment by JackTerok** [comment] 2020-07-19 21:32
Following steps that I've done:

1.) Start MM in server only so I can connect from another PC(but problems are the same no matter server or client mode)

2.) Open the remote MM page on my PC

3.) Now the server log shows all API calls. The ones going to the Tesla Server are looking good. The ones to the local address return: 
[2020-07-19 22:05:00.474] [LOG]    MMM-Powerwall: {"response":[],"count":0}

In the Client debug window it only shows the successful API calls and the interface shows the local variables with NaN.

4.) reload the page. Now the local API calls are successful and look like this:
Received SOE: {"IP":"192.168.2.206","soe":63.30593089546127}

Received Aggregates:

{
   "ip":"192.168.2.206",
   "aggregates":{
      "site":{
         "last_communication_time":"2020-07-19T23:24:59.490465511+02:00",
         "instant_power":29,
         "instant_reactive_power":32,
         "instant_apparent_power":43.18564576337837,
         "frequency":0,
         "energy_exported":2700356,
         "energy_imported":569373,
         "instant_average_voltage":405.06317536074954,
         "instant_total_current":0,
         "i_a_current":0,
         "i_b_current":0,
         "i_c_current":0,
         "timeout":1500000000
      },
      "battery":{
         "last_communication_time":"2020-07-19T23:24:59.49029577+02:00",
         "instant_power":360,
         "instant_reactive_power":10,
         "instant_apparent_power":360.1388621073821,
         "frequency":50.034,
         "energy_exported":5684240,
         "energy_imported":6578830,
         "instant_average_voltage":234.5,
         "instant_total_current":-9.200000000000001,
         "i_a_current":0,
         "i_b_current":0,
         "i_c_current":0,
         "timeout":1500000000
      },
      "load":{
         "last_communication_time":"2020-07-19T23:24:59.49029577+02:00",
         "instant_power":389.5,
         "instant_reactive_power":62.5,
         "instant_apparent_power":394.4825724921191,
         "frequency":0,
         "energy_exported":0,
         "energy_imported":1847980,
         "instant_average_voltage":405.06317536074954,
         "instant_total_current":0.9615783998461747,
         "i_a_current":0,
         "i_b_current":0,
         "i_c_current":0,
         "timeout":1500000000
      },
      "solar":{
         "last_communication_time":"2020-07-19T23:24:59.490583504+02:00",
         "instant_power":-5,
         "instant_reactive_power":21,
         "instant_apparent_power":21.587033144922902,
         "frequency":0,
         "energy_exported":4881195,
         "energy_imported":7642,
         "instant_average_voltage":405.0458548526738,
         "instant_total_current":0,
         "i_a_current":0,
         "i_b_current":0,
         "i_c_current":0,
         "timeout":1500000000
      }
   }
}

Also, all API Calls get shown on Server and Client log.

6.) now with every refresh there is a successful API call to all endpoints but always only one and no repeat. Higher or lower refresh interval didn't make a difference.

**Comment by MikeBishop** [comment] 2020-07-20 03:57
Thanks for your patience with this.  Besides simply wanting to help you get this working, I'm particularly curious because that log line *looks* like the output from doTeslaApi, not anything with the local Powerwall at all, but the only one(s) that return arrays for "result" are getting products/vehicles.  But I don't see how getting an empty list for that would block the rest.

On a branch, I've added some extra logging that might help figure out what the issue is.  If you would:

    git fetch
    git checkout debug/local_calls

...and then re-run, hopefully the extra logging will help us pin down what's going on here.  Again, thanks for your patience and your help with debugging.

**Comment by JackTerok** [comment] 2020-07-20 14:58
The API calls that return empty in the first run are going to Mirror $ https://owner-api.teslamotors.com/api/1/vehicles.
Of course, they return empty since this account doesn't have a car associated with it.

[Output.txt](https://github.com/MikeBishop/MMM-Powerwall/files/4948447/Output.txt)

I attached the complete log with anonymized personal data and a few comments.

**Comment by MikeBishop** [comment] 2020-07-20 17:35
Okay, so that seems like a red herring.  It's correct for that to return an empty array, since you don't have a Tesla vehicle; modifying my code to force-return an empty array doesn't break anything using a config that matches yours, either -- the code for displaying vehicle data sees there are no cars to display and no vehicle-focused tile and just skips.

I found a possible issue here:
> [2020-07-20 16:48:47.388] [LOG]    MMM-Powerwall: UpdateLocal{"powerwallIP":"192.168.2.206","twcManagerIP":null,"twcManagerPort":8080,"updateInterval":4500,"username":"DELETED","siteID":"DELETED","resyncInterval":9500}
> [2020-07-20 16:48:47.398] [LOG]    MMM-Powerwall: Local: Aborting because credentials aren't ready
> [2020-07-20 16:48:47.402] [LOG]    MMM-Powerwall: Read Tesla API tokens from file

If siteID isn't specified in the config, it won't be specified in the request for local data until the Tesla API account has been validated, and the code simply returns the local SOE.  But you're manually specifying a siteID, which the server thinks means it should be able to access the cloud API as well; the credentials haven't been sorted yet at that point, so it fails the request.

7849cd0 just makes the client request local data again after the Tesla API is configured -- I'd like to see if that gets you up and running.  A better fix, and what I'll actually put in the main branch, would be to skip the cloud portion of the SOE check if the cloud APIs aren't yet available, just as if the siteID had been omitted.

**Comment by JackTerok** [comment] 2020-07-20 19:21
Progress. Now you don't need the second refresh. All data is displayed on the first run. But we are still stuck after the first run and dont get any data refresh.

**Comment by MikeBishop** [comment] 2020-07-21 02:55
Anything in the console? Does the event for requesting local data fire repeatedly, or just once? Are there uncaught exceptions?

**Comment by JackTerok** [comment] 2020-07-21 17:24
Changing the intervals didn't change anything. Since the last changes if I reload the page the request local data event fires 2 times at once and then nothing. No errors or exceptions etc.

**Comment by MikeBishop** [comment] 2020-07-22 13:58
Hrm.  2b686f9 makes it check periodically for overdue timers in a different path; that's worth a shot.  I've also added some extra logging to the debug console for outgoing messages.  If this doesn't resolve it, could you right-click on the console, "Save As..." and [send me](mailto:mbishop@evequefou.be) the logged output?

**Comment by JackTerok** [comment] 2020-07-22 16:52
Latest changes didn't make a difference. I've sent you an email.

**Comment by MikeBishop** [comment] 2020-07-22 17:51
It looks like everything that's purely event-based is happening (the API gets configured at startup, the request for local data fires, the success message from node_helper arrives, and the updates that happen immediately after API configuration success fire), but no timers are ever executing.

Timers not firing is the expected behavior while the module is suspended, and I see from your log that some other modules are suspended.  I've added some console logging around suspend/resume to confirm, but I'm wondering if something is sending a USER_PRESENCE: false notification that causes this module to suspend as well.

**Comment by JackTerok** [comment] 2020-07-22 18:31
Tried the new build. Non of the new suspension messages get triggered.

http://prntscr.com/tmrgdu

**Comment by MikeBishop** [comment] 2020-07-22 19:27
It's almost as if nothing using timers works for you.  Even if nothing else happens, the setInterval call should result in either a request for local updates or a message that the module is suspended.  (I added an event when the timer fires regardless of what it does, just to see if it does in fact fire, but I suspect it doesn't.)  But if that were a generic problem on your system, I don't really understand how *anything* would work, including your clock module.

The clock module sends a notification once per second if seconds are displayed; I could certainly piggyback on that and check for overdue timers, but that would just be a band-aid.

**Comment by JackTerok** [comment] 2020-07-22 19:33
I will do a complete raspibian reinstall tomorrow and see if that fixes it.

**Comment by MikeBishop** [comment] 2020-07-22 19:39
I just added the clock second bandaid.  I'm hesitant to put it into the main branch, but I'm curious whether it works for you.  :-)  You'll see an extra five-second delay beyond whatever timeout you specify, because it doesn't act until a timer is five seconds overdue, but it should still act.

**Comment by JackTerok** [comment] 2020-07-22 22:06
With the last update i get "Timer fired" events in the client console. But it dosn't do anything besides show this event.

**Comment by MikeBishop** [comment] 2020-07-23 01:16
That might be even weirder.

**Comment by JackTerok** [comment] 2020-07-24 18:24
Did a complete reinstall of everything. Still same problems. Thats so strange.

**Comment by MikeBishop** [comment] 2020-07-24 19:26
I am flummoxed.  With a reinstall, I assume that you're running current versions of everything, and your browser is presumably up-to-date as well.  I've set up a second instance of MagicMirror and have the config that you're using (with my PW's IP address, of course) and everything works.  Even if I comment out the line that actually sets the timer, it discovers that it needs to re-run every ~10-15 seconds because of the clock events on this branch and updates slowly.

I truly wish I could debug on your machine; something is going on, and I'd like to get to the bottom of it.  I'm not sure what else to try on a machine I can't connect to and trace.

If you're comfortable in your browser's dev tools, perhaps you could set a few breakpoints to see if anything looks odd.  Some spots to try:

- on line 310, tracing into the `doTimeout()` call to ensure that it actually makes the setInterval time (and that the delay is something sensible; if it's setting the timers incorrectly high for some reason, that might also cause the behavior you're seeing)
- on line 558, see whether `checkTimeouts()` ever finds that it needs to run an overdue timer.  If not, break a few lines earlier and look at `this.timeouts` for any ideas why it doesn't.

Also, I found that some of my new logging calls were capitalized incorrectly (log, Log), so there might be some additional traces with the latest commit on the debug/local_calls branch.

**Comment by MikeBishop** [comment] 2020-12-10 16:23
I'm closing this for now; if you're still not able to get it to work, I'd be happy to help debug further.

**Closed by MikeBishop** 2020-12-10 16:23 UTC
